[tools]
aws = "latest"
flux2 = "latest"
go = "latest"
helm = "latest"
kops = "v1.30.4"
kubectl = "latest"
kubectx = "0.9.4"
kubens = "latest"
pipx = "latest"
"pipx:aws-sso-util" = "latest"
"pipx:pylint" = "latest"
python = "latest"
rust = "latest"
teleport-ent = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
