[tools]
aws = "latest"
flux2 = "latest"
go = "latest"
helm = "latest"
kops = "v1.30.4"
kubectl = "1.30.14"
kubectx = "0.9.4"
kubens = "latest"
pipx = "latest"
"pipx:aws-sso-util" = "latest"
"pipx:pylint" = "latest"
python = "latest"
rust = "latest"
teleport-ent = "14.1.1"
terraform = "1.11.3"
terraform-docs = "latest"
terragrunt = "0.45.0"
