[tools]
aws = "latest"
bat = "latest"
flux2 = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
helm-docs = "latest"
jq = "latest"
kops = "v1.30.4"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
neovim = "latest"
pipx = "latest"
"pipx:aws-sso-util" = "latest"
"pipx:pylint" = "latest"
pre-commit = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
sops = "latest"
stern = "latest"
task = "latest"
teleport-ent = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
yq = "latest"
